"""Paths, conversions, colors, and fonts shared by every dashboard module."""

import os

_HERE    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Load a gitignored strava-data/.env into the environment (if present) so a local
# MAPTILER_KEY doesn't have to be exported by hand. CI passes the key as a real env
# var, so load_dotenv is a no-op there. Best-effort: never fail the build if the
# file or the dependency is absent.
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(_HERE, ".env"))
except ImportError:
    pass

from nerd_common.tokens import (
    ACCENT, ACCENT_DIM, ACCENT_GLOW,
    BG_BASE, BG_ELEVATED, BG_GLASS, BG_SURFACE,
    BORDER, BORDER_SUBTLE,
    PLOT_FONT_FAMILY, PLOTLY_CDN,
    TEXT_PRIMARY, TEXT_SECONDARY, TEXT_TERTIARY,
    TITLE_FONT_FAMILY,
)

DATA_DIR = os.path.join(_HERE, "data")
ACT_CSV      = os.path.join(DATA_DIR, "activities.csv")
SEG_CSV      = os.path.join(DATA_DIR, "segments_summary.csv")
SEG_EFF_CSV  = os.path.join(DATA_DIR, "segment_efforts.csv")
STREAMS_DIR  = os.path.join(DATA_DIR, "streams")
# Static, checked-in build assets (NOT fetched data): e.g. the Places vector
# basemap, regenerated by strava-data/tools/gen_basemap.py.
ASSETS_DIR   = os.path.join(_HERE, "assets")

# Generated output (gitignored). The Running Log dir is the GitHub Pages publish root.
OUT_HTML = os.path.normpath(os.path.join(_HERE, "..", "Running Log", "strava.html"))

# MapLibre GL JS — powers the Places hero's real tiled basemap (Street / Terrain).
# CSS + JS, both render-blocking in <head> like PLOTLY_CDN. The page guards every
# `window.maplibregl` call, so a blocked CDN degrades the hero to its tile-free
# "Glow" look rather than breaking.
MAPLIBRE_CDN = (
    '<link href="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css" rel="stylesheet">'
    '<script src="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js"></script>'
)

# MapTiler API key for the Street/Terrain basemap tiles, read from the build
# environment (a GitHub Actions secret in deploy.yml). Empty -> the hero runs
# Glow-only and the Street/Terrain buttons disable themselves. The key ends up in
# the published static HTML, so it MUST be domain-restricted to ducktapegirl.github.io
# in the MapTiler dashboard.
MAPTILER_KEY = os.environ.get("MAPTILER_KEY", "")

KM_TO_MI = 0.621371
M_TO_FT  = 3.28084

SPORT_DISPLAY = {
    "Running":          "Running",
    "MountainBikeRide": "Mountain Bike Ride",
    "Other":            "Other",
}

# Categorical sport colors — tuned for hue separation, matching the running-log
# workout-type palette (teal / amber / slate). Used by both themes.
SPORT_COLORS = {
    "Running":          "#2dd4bf",
    "MountainBikeRide": "#f59e0b",
    "Other":            "#8b949e",
}

# Trail Running — violet, distinct from teal Running and amber MTB
TRAIL_RUN_COLOR = "#a78bfa"

# Hiking — green, distinct from the run/MTB/trail-run hues above
HIKE_COLOR = "#4ade80"

# Dark-theme design tokens (BG_*/BORDER*/TEXT_*/ACCENT*/fonts/PLOTLY_CDN) are
# imported from nerd_common.tokens above. The theme toggle JS overrides these at
# runtime via Plotly.relayout reading the CSS custom properties.
GRID = BORDER_SUBTLE  # grid/zeroline colour (identical value to BORDER_SUBTLE)

# Semantic trend colors for segment bars
FASTER  = "#2dd4bf"
SLOWER  = "#f87171"
NEUTRAL = "#58a6ff"
ELEVATION_COLOR = "#a78bfa"  # violet for elevation, distinct from accent blue

# 92129 (Rancho Penasquitos, San Diego) — fixed map center
MAP_CENTER_LAT = 32.9545
MAP_CENTER_LON = -117.0910

# Used by segment "fastest"/"consistency" card builders (rollups_cards.py)
RUN_EMOJI = "\U0001f3c3‍♀️"   # woman running
MTB_EMOJI = "\U0001f6b5‍♀️"   # woman mountain biking
